logLevel: info
loopDurationSecond: 2
loseRatioLimit: 0.25
servers:
  - www.baidu.com
  - qq.com
  - youku.com
  - v.qq.com
  - music.qq.com
  - mail.qq.com
  - cloud.tencent.com
  - ihk.ltd
  - csdn.net
  - cnblog.com
  - hao123.com
  - aliyun.com
  - taobao.com
  - 1688.com
  - www.tmall.com
  - jd.com
  - zhihu.com
  - 58.com
  - huya.com
  - www.zhipin.com
  - hu60.cn
  - igo.pub
  - www.runoob.com
  - vip.com
  - suning.com
  - www.jianshu.com
  - cn.bing.com
  - filfox.info
  - fanyi.qq.com
  - www.qunar.com
  - kankan.eastday.com
  - flights.ctrip.com
  - www.kuaishou.com
  - www.douyin.com
  - www.4399.com
  - www.autohome.com.cn
  - www.7k7k.com
  - hao.qq.com
  - www.sina.com.cn
  - www.anjuke.com
  - www.china.com
  - tieba.baidu.com
  - www.ifeng.com
  - www.eastmoney.com
  - sz.ganji.com
  - junshi.aigobook.com
  - www.wenjuan.com
  - www.2345.com
  - shenzhen.baixing.com
  - military.miercn.com
  - www.dianping.com
  - tg.602.com
  - www.boc.cn
  - novel.contentchina.com
  - www.cnstock.com
  - www.sitestar.cn
  - mail.top
  - www.zaobao.com
  - www.10086.cn
  - www.haomaimai.com
  - www.huanqiu.com
  - www.265.com
  - www.cctv.com
  - www.gome.com.cn
  - youhui.pinduoduo.com
  - www.kugou.com
  - www.yinyuetai.com
  - music.taihe.com
  - www.xiami.com
  - www.xiaohongshu.com
  - www.huawei.com
  - www.huaweicloud.com
  - v.6.cn
  - www.bytedance.com
  - www.ximalaya.com
  - www.mi.com
  - www.hihonor.com
  - bbs.vivo.com.cn
  - www.vivo.com.cn
  - www.zhiji.com
  - www.yhd.com
  - www.yy.com
  - beijing.fangdd.com
  - www.maodou.com
  - www.qiushibaike.com
  - www.duba.com
  - tp.9377j.com
  - www.gmw.cn
  - cn.chinadaily.com.cn
  - www.777ppt.com
  - www.cmbc.com.cn
  - pbank.psbc.com
  - www.guazi.com
  - www.lagou.com
  - landing.zhaopin.com
  - www.sogou.com
  - www.moonbasa.com
  - opentuna.cn
  - www.xinhuanet.com
  - www.cndns.com
  - www.dnspod.cn
  - fanyi.qq.com
  - 123.sogou.com
  - y.code.17tanwan.com
  - m.ce.cn
  - www.xiaomiyoupin.com
  - hd.oppo.com
  - lego.mgtv.com
  - www.msn.cn
  - www.mhcf.net
  - couqiao.net
  - www.wispx.cn
  - www.banto.cn
  - www.xtboke.cn
  - 12gb.cn
  - cway.top
  - www.sqyai.com
  - vv1234.cn
  - sad.gs
  - www.iyouhun.com
  - nowtime.cc
  - ll00.cn
  - too.pub
  - loc.cc
  - liujianjun.net
  - www.shifeiti.cn
  - xuthus.cc
  - eblog.ink
  - wanbk.net
  - hjtxt.club
  - lovefc.cn
  - wapjin.com
  - ii.do
  - guozhivip.com
  - www.endata.com.cn
  - maoyan.com
  - www.vmovier.com
  - she.xitek.com
  - dig.chouti.com
  - user.guancha.cn
  - bbs.hupu.com
  - www.pearvideo.com
  - www.acfun.cn
  - xueqiu.com
  - 36kr.com
  - www.forbeschina.com
  - www.imdb.com
  - www.poco.cn
  - music.migu.cn
  - 500px.com.cn
  - www.cnu.cc
  - photos.oneplus.com
  - tuchong.com
  - photo.fengniao.com
  - bcy.net
  - huaban.com
  - top10.ui.cn
  - www.ycyui.com
  - www.zhisheji.com
  - gracg.com
  - uiiiuiii.com
  - product.pconline.com.cn
  - phat.jd.com
  - img30.360buyimg.com
  - bang.dangdang.com
  - www.taptap.com
  - www.toubang.tv
  - www.kuaikanmanhua.com
  - www.dm5.com
  - www.iimedia.cn
  - report.amap.com
  - statics.oneplus.cn



